# Create app quickapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickapp-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: thongle0610/quickapp:vk8s
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
          ports:
            - containerPort: 5000
            - containerPort: 5001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"                   
            - name: ASPNETCORE_URLS
              value: "https://+:5001;http://+:5000"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: "B@oL0ng@123456"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/https/aspnetapp.pfx"
---
# Create app node port for quickapp
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  selector:
      app: app2
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 31080
    - name: https
      port: 5001
      targetPort: 5001
      nodePort: 31443